# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.6.1-alpine3.9"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v                                   
  - bundle install --path vendor

rspec:
  script:
  - rspec spec