# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.6"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v        
  - bundle exec rake install                           
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  script:
  - rubocop

rspec:
  script:
  - rspec spec