AllCops:
  TargetRubyVersion: 2.6

Layout/AlignHash:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 25

Naming/FileName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/NumericLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
