query ($search: String, $type: MediaType) {
	Media (search: $search, type: $type) {
		id
		title {
			romaji
			english
			native
		}
		type
		format
		status
		description
		startDate {
			year
			month
			day
		}
		endDate {
			year
			month
			day
		}
		season
		episodes
		duration
		chapters
		volumes
		countryOfOrigin
		isLicensed
		source
		hashtag
		trailer {
			id
			site
		}
		updatedAt
		coverImage {
            large
			medium
        }
		bannerImage
		genres
		synonyms
        averageScore
		meanScore
		popularity
		trending
		tags {
			id
			name
			description
			category
			rank
			isGeneralSpoiler
			isMediaSpoiler
			isAdult
		}
		isAdult
		nextAiringEpisode {
            timeUntilAiring
            episode
        }
		externalLinks {
			id
			url
			site
		}
		streamingEpisodes {
			title
			thumbnail
			url
			site
		}
		rankings {
			id
			rank
			type
			format
			year
			season
			allTime
			context
		}
		siteUrl
        modNotes
	}
}